# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libqmlchewing_plugin

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Bridge between QML and chewing
Version:    0.1
Release:    2
Group:      Qt/Qt
License:    LGPLv2
URL:        https://github.com/hanhsuan/libqmlchewing-plug
Source0:    %{name}-%{version}.tar.gz
Source100:  qmlchewing.yaml
Requires:   libchewing
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(chewing)

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 ./src/qmlchewing.pro

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/qt5/qml/H/H/chewing/libQmlChewing.so
%{_libdir}/qt5/qml/H/H/chewing/qmldir
# >> files
# << files
